// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHiw8p4rQluHSHeCbR3-xrXuzDgoPRPHM',
    appId: '1:168171725571:web:4bc2c4a61d041eec563f36',
    messagingSenderId: '168171725571',
    projectId: 'notifications-test-ce00b',
    authDomain: 'notifications-test-ce00b.firebaseapp.com',
    storageBucket: 'notifications-test-ce00b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0T6HtWdBm3HIBNsHqxGEHjqkNOavTehk',
    appId: '1:168171725571:android:78ff98946138d312563f36',
    messagingSenderId: '168171725571',
    projectId: 'notifications-test-ce00b',
    storageBucket: 'notifications-test-ce00b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADkd6irGwTDYFUkUjLtMvuaUTCeBe7aZo',
    appId: '1:168171725571:ios:9480a8e965635afc563f36',
    messagingSenderId: '168171725571',
    projectId: 'notifications-test-ce00b',
    storageBucket: 'notifications-test-ce00b.firebasestorage.app',
    iosBundleId: 'com.example.stargate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADkd6irGwTDYFUkUjLtMvuaUTCeBe7aZo',
    appId: '1:168171725571:ios:9480a8e965635afc563f36',
    messagingSenderId: '168171725571',
    projectId: 'notifications-test-ce00b',
    storageBucket: 'notifications-test-ce00b.firebasestorage.app',
    iosBundleId: 'com.example.stargate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHiw8p4rQluHSHeCbR3-xrXuzDgoPRPHM',
    appId: '1:168171725571:web:c3fb38096e31f4a7563f36',
    messagingSenderId: '168171725571',
    projectId: 'notifications-test-ce00b',
    authDomain: 'notifications-test-ce00b.firebaseapp.com',
    storageBucket: 'notifications-test-ce00b.firebasestorage.app',
  );
}
